import "@/app/globals.css";
import '@flaticon/flaticon-uicons/css/all/all.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`font-yekanBakh antialiased`}>
        {children}
      </body>
    </html>
  );
}
